apiVersion: v1
kind: ServiceAccount
metadata:
  name: standalone-cinder-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cinder-rbac
subjects:
  - kind: ServiceAccount
    name: standalone-cinder-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: standalone-cinder-provisioner
  namespace: kube-system
spec:
  securityContext:
    runAsUser: 1001
  # tolerations:
  # - key: node.cloudprovider.kubernetes.io/uninitialized
  #   value: "true"
  #   effect: NoSchedule
  # - key: node-role.kubernetes.io/master
  #   effect: NoSchedule
  serviceAccountName: standalone-cinder-provisioner
  containers:
  - name: standalone-cinder-provisioner
    image: docker.io/k8scloudprovider/cinder-provisioner:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: OS_CINDER_ENDPOINT
      value: http://{{ cluster_api_address }}:8776/v3
    - name: OS_USERNAME
      value: {{ cinder_username }}
    - name: OS_PROJECT_ID
      value: {{ cinder_tenant_name }}