apiVersion: v1
kind: ServiceAccount
metadata:
  name: standalone-cinder-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cinder-rbac
subjects:
  - kind: ServiceAccount
    name: standalone-cinder-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: standalone-cinder-provisioner
  namespace: kube-system
  labels:
    k8s-app: standalone-cinder-provisioner
spec:
  selector:
    matchLabels:
      k8s-app: standalone-cinder-provisioner
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: standalone-cinder-provisioner
    spec:
      nodeSelector:
        mongodb: "dump-backups"
      securityContext:
        runAsUser: 1001
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: standalone-cinder-provisioner
      containers:
      - name: standalone-cinder-provisioner
        image: docker.io/k8scloudprovider/cinder-provisioner:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: OS_CINDER_ENDPOINT
          value: http://{{ cluster_api_address }}:8776/v3
        - name: OS_USERNAME
          value: {{ cinder_username }}
        - name: OS_PROJECT_ID
          value: {{ cinder_tenant_name }}