apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-backup
  labels:
    app: mongo-dump
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: mongodump
        image: mongo
        command: ["mongodump","--host","mongodb:27017","--out", "/mnt/nfs/var/nfsshare/backups/`date +'%m-%d-%y'`"]
        volumeMounts:
          - mountPath: dump
            name: mongo-dumps
      volumes:
      - name: mongo-dumps
        hostPath:
          path: /mnt/nfs/var/nfsshare/backups
      nodeSelector:
        node: node2
      restartPolicy: OnFailure
