apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: db
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        command:
       - mongod
       - "--dbpath"
       - /mnt/nfs/var/nfsshare
        ports:
        - containerPort: 27017
          name: db
        # volumeMounts:
        # - name: nfs
        #   mountPath: /mnt/nfs/var/nfsshare/
      volumes:
      - name: nfs
        hostPath:
          path: /mnt/nfs/var/nfsshare
      nodeSelector:
        node: node2
